name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Running Page Speed Insights
      uses: jakepartusch/psi-action@v1
      id: psi
      with:
        url: "https://oxypomme.github.io/"
        threshold: 70
        strategy: mobile
